create table if not exists public.habitts (
  "id" bigint generated by default as identity primary key,
  "Name" text not null,
  "Goal" numeric not null,
  "Unit" text not null,
  "Icon" text,
  "ReminderTime" time,
  "User" text not null,
  "Habitt" boolean not null default false
);

create index if not exists habitts_user_idx on public.habitts ("User");
